name: 'Install MLKit'
description: 'Installs the MLKit compiler'
inputs:
  version:
    description: 'Version to install (or "latest")'
    required: false
    default: 'latest'
runs:
  using: "composite"
  steps:
    - id: setup-os
      shell: bash
      run: |
        OS_NAME=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
        if [ "$OS_NAME" = "macos" ]; then
          OS_NAME="darwin"
        elif [ "$OS_NAME" != "linux" ]; then
          echo "Error: Unsupported operating system '${{ runner.os }}'. Only Linux and macOS are supported."
          exit 1
        fi
        echo "MLKIT_OS=$OS_NAME" >> "$GITHUB_ENV"
    - id: install-dependencies
      shell: bash
      run: |
        if [ "$MLKIT_OS" = "darwin" ]; then
          echo "Installing GMP library on macOS..."
          brew install gmp
          echo "Checking GMP library installation..."
          ls -l /usr/local/lib/libgmp* || echo "No GMP libraries found in /usr/local/lib"
          # Create symlink for GMP if needed (for Apple Silicon Macs where Homebrew uses /opt/homebrew)
          BREW_PREFIX="$(brew --prefix)"
          if [ "$BREW_PREFIX" != "/usr/local" ]; then
            echo "Checking GMP library in Homebrew prefix..."
            ls -l "$BREW_PREFIX/lib/libgmp*" || echo "No GMP libraries found in $BREW_PREFIX/lib"
          fi
          if [ ! -L /usr/local/opt/gmp ] && [ ! -e /usr/local/opt/gmp ] && [ -e "$BREW_PREFIX/opt/gmp" ]; then
            echo "Creating symlink from $BREW_PREFIX/opt/gmp to /usr/local/opt/gmp"
            sudo mkdir -p /usr/local/opt
            sudo ln -s "$BREW_PREFIX/opt/gmp" /usr/local/opt/gmp
          fi
        fi
    - id: fetch
      uses: dsaltares/fetch-gh-release-asset@1.1.0
      with:
        repo: 'melsman/mlkit'
        version: ${{ ((inputs.version == 'latest') && 'latest') || format('tags/v{0}', inputs.version) }}
        regex: true
        file: "mlkit-bin-dist-${{ env.MLKIT_OS }}.tgz"
        target: 'mlkit-install-dir/'
    - id: install
      shell: bash
      working-directory: 'mlkit-install-dir/'
      run: |
        tar xvf mlkit-bin-dist-${{ env.MLKIT_OS }}.tgz
        mkdir -p "$HOME/.local/bin"
        make -C mlkit-bin-dist-${{ env.MLKIT_OS }} install PREFIX=$HOME/.local
        echo "SML_LIB=$HOME/.local/lib/mlkit" >> "$GITHUB_ENV"
    - id: cleanup
      shell: bash
      run: rm -rf mlkit-install-dir
    - id: report
      shell: bash
      run: mlkit --version
